### PR TITLE
Updating PUMLs to current release version.

### PR DESCRIPTION
**Pull request by jtreher**

### CODE REVIEW

**Comment by yanjustino** [comment]
@jtreher thank you for your contributions! Before accepting your commit I need to fix how de library leads with standard C4 pluntuml files and embedded c4 resources. After that, I'll join your code in the main branch, OK?

best regards

**Comment by jtreher** [comment]
Oh, I didn't realize that this would be a breaking change. Please let me
know if you need me to help with that.

Justin

**Comment by yanjustino** [comment]
@jtreher no problem! I've worked on this fix! soon I'll publish a new version! I'd like this opportunity to appreciate your PR's and suggestions.

**Comment by yanjustino** [comment]
@jtreher sincerely, I need to set up de XUnit project and write tests...

**Comment by jtreher** [comment]
@yanjustino I have already started the xunit commit last night. I don't mind seeing the unit tests through to completion. I'm just not sure what approach will work best for some of the volatile static dependencies such as the file system. It might take some refactoring, so for not I'll just cover what I can to avoid making code changes while introducing what can be covered. https://github.com/jtreher/c4sharp/tree/add-tests

**Comment by yanjustino** [comment]
@jtreher the last commit into the main branch contemplate the new version of this files. Also, I'd set up the test project on the solution.

**Pull request closed without merging**
